

GET http://localhost:3000/user/list HTTP/1.1

###

POST http://localhost:3000/user/create HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "lastName": "sample",
    "email": "jose@jose.com",
    "password": "123456"

}

###

PUT http://localhost:3000/user/update/654e4d2ad5a91a11698cae74 HTTP/1.1
content-type: application/json

{
    "role": "admin"
}